### ISSUE TITLE
User-friendly UI for ImgIN

### ISSUE THREAD

**Issue by SanjanaBankar** [RituKumari98/imgIN#16]
Hello,
@RituKumari98 
I believe I can create the following elements:-
Elements like a search bar, Search Criteria, Search Button, Image Display Area, Loading Indicator, Navigation menu, and Footer.

These elements collectively create a user-friendly and efficient UI for an image scraping tool, providing users with the necessary functionalities to search, browse, and manage scraped images effectively.

Please assign it under GSSOC'24! Looking forward to collaborating on the project!

Regards,
Sanjana

**Comment by krishkh** [comment]
You mean you will create the entire project? as there is nothing in this project to begin with?

**Comment by SanjanaBankar** [comment]
> You mean you will create the entire project? as there is nothing in this project to begin with?

No I was thinking of a very basic UI, as there is quite literally nothing to begin with, and maybe the maintainer/collaborator will add files if any??

**Comment by krishkh** [comment]
haha lets hope the project admin does do that.
