### ISSUE TITLE
Update Steps of Contribution and Pull request Guidelines 

### ISSUE THREAD

**Issue by Sibam-Paul** [RituKumari98/imgIN#19]
### Should mention the guidelines of the steps to Contribute i.e. how to make pull request and git command

**Didn't find steps to contribute**
![image](https://github.com/RituKumari98/imgIN/assets/158052549/19061a80-2439-4178-ba38-f4e97a04c2cb)

**I want to work on this Readme issue**
_Please assign me this issue_

**I am working under GSSOC'24**

_Plz give tags:-_

- GSSOC'24
- Level 1

_I am working on it assign it to me so that I can contribute_

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
