### ISSUE TITLE
CODE_OF_CONDUCT.md file is missing

### ISSUE THREAD

**Issue by Meetjain1** [RituKumari98/imgIN#26]
CODE_OF_CONDUCT.md file is missing in our repository @RituKumari98 mam Assign this issue to me I will add it.

**Comment by Meetjain1** [comment]
just created a PR #40 for this issue @RituKumari98 Mam , Please have a look on this pr . Thankyou

**Comment by officeneerajsaini** [comment]
@Meetjain1  close this issue as a completed.

**Comment by Meetjain1** [comment]
@officeneerajsaini sure
