### ISSUE TITLE
Creating navbar

### ISSUE THREAD

**Issue by Sibam-Paul** [RituKumari98/imgIN#30]
***Hey s for the project I wanna work on this**

**Creating a navbar**

- with image
- and links

Also making it responsive for various screen 

_Please assign me this issue I wanna work on it_

Under Gssoc'24

**Comment by hritika2409** [comment]
@RituKumari98  Can you please assign me this task for Creating a navbar. Please assign me this issue I wanna work on it Under Gssoc'24.

**Comment by krati234** [comment]
assign this to me please

**Comment by harshcodesit** [comment]
Hey @RituKumari98 
I have worked on the similar project in a hackathon

repo link:-https://github.com/harshcodesit/AIETM-Hackathon-2024

I can create an immersive Navbar

**Comment by Satuti99** [comment]
Hello sir @RituKumari98   I would like to work on this issue. Kindly assign this task to me .
