### ISSUE TITLE
CONTRIBUITING.md file is missing

### ISSUE THREAD

**Issue by Meetjain1** [RituKumari98/imgIN#42]
RIght now CONTRIBUITING.md file is missing in our repository , @RituKumari98 mam Assign this issue to me , I will add it. Thankyou

**Comment by Meetjain1** [comment]
@RituKumari98

**Comment by suhanipaliwal** [comment]
Duplicate #20

**Comment by Meetjain1** [comment]
@suhanipaliwal ok
