### ISSUE TITLE
Creating a landing page

### ISSUE THREAD

**Issue by Sibam-Paul** [RituKumari98/imgIN#64]
### To create a landing page where there will be all the details about the project 

**Please assign me this issue under GSSOC'24 so that I can work on it**

**Comment by Gautamali** [comment]
To create a landing page where there will be all the details about the project

Please assign me this issue under GSSOC'24 so that I can work on it

**Comment by Priyanjali24** [comment]
To create a landing page where there will be all the details about the project

Please assign me this issue under GSSOC'24 .

**Comment by jaiyankargupta** [comment]
HEY @Sibam-Paul, Please assign this issue.
